# -*- coding: utf-8 -*-
"""dashboard.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p_xta2xArpd0Rlrlxq9kNRqKvKcqOs5Z
"""

# Stop streamlit dulu
import subprocess
subprocess.run(["pkill", "-f", "streamlit"])

# Install dependencies
!pip install streamlit pyngrok -q

!ngrok authtoken 3FISl0jtLPOGEz4XaRWLaS78h9N_4UDi5sMMLQzUkpze9moNu

import subprocess, time
from pyngrok import ngrok

subprocess.run(["pkill", "-f", "streamlit"])
time.sleep(2)
subprocess.Popen(["streamlit", "run", "/content/dashboard.py", "--server.port=8501"])
time.sleep(3)
url = ngrok.connect(8501)
print("Buka dashboard di:", url)

import time
time.sleep(5)

import urllib.request
try:
    urllib.request.urlopen("http://localhost:8501")
    print("Streamlit JALAN ✅")
except:
    print("Streamlit BELUM JALAN ❌")